title: "Data Sourcing - v2.0.2" 
changelog:
  categories:
    - title: "🔧 Breaking Changes"
      labels:
        - breaking-change
    - title: "🚀 New Features"
      labels:
        - new-feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug-fix
template: |
  ## Data Sourcing - v2.0.2

  ### 🔧 Breaking Changes
  - List of breaking changes here.

  ### 🚀 New Features
  - List of new features here.

  ### 🐛 Bug Fixes
  - List of bug fixes here.
