changelog:
  categories:
    - title: 🔧 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 New Features
      labels:
        - dependencies
    - title: 🐛 Bug Fixes
      labels:
        - dependencies