name-template: 'Release $NEXT_PATCH_VERSION 🌟'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧹 Chores'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'docs'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '🔍 Tests'
    label: 'test'

change-template: '- $TITLE (#$NUMBER) by @${{PR.author.login}}'
template: |
  ## Changes in this Release
  $CHANGES

  **Contributors**:
  $CONTRIBUTORS
