categories:
  - title: '🔧 Breaking Changes'
    labels:
      - breaking-change
  - title: '🚀 New Features'
    labels:
      - new-feature
      - feat
  - title: '🐛 Bug Fixes'
    labels:
      - bug-fix
      - fix
  - title: '📝 Documentation'
    labels:
      - documentation
      - docs
  - title: '🛠 Code Refactoring'
    labels:
      - refactor
  - title: '🎨 Styling'
    labels:
      - style
  - title: '🔍 Tests'
    labels:
      - test
  - title: '🏗 Build'
    labels:
      - build
  - title: '⚙️ Chore'
    labels:
      - chore
  - title: '⏪ Reverts'
    labels:
      - revert
  - title: '⏩ Performance Improvements'
    labels:
      - perf
  - title: '🔄 Continuous Integration'
    labels:
      - ci
  - title: '💚 Maintenance'
    labels:
      - maintenance
