name-template: 'Release $NEXT_PATCH_VERSION 🌟'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧹 Chores'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'docs'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '🔍 Tests'
    label: 'test'
  - title: '💄 Style'
    label: 'style'
  - title: '⚡️ Performance'
    label: 'perf'
  - title: '📦 CI/CD'
    label: 'ci'
change-template: '- $TITLE (#$NUMBER) by @${{PR.author.login}}'
template: |
  ## Changes in this Release

  ### 🚀 Features
  $CHANGES_FOR_CATEGORY_FEAT

  ### 🐛 Bug Fixes
  $CHANGES_FOR_CATEGORY_FIX

  ### 🧹 Chores
  $CHANGES_FOR_CATEGORY_CHORE

  ### 📝 Documentation
  $CHANGES_FOR_CATEGORY_DOCS

  ### 🔧 Refactoring
  $CHANGES_FOR_CATEGORY_REFACTOR

  ### 🔍 Tests
  $CHANGES_FOR_CATEGORY_TEST

  ### 💄 Style
  $CHANGES_FOR_CATEGORY_STYLE

  ### ⚡️ Performance
  $CHANGES_FOR_CATEGORY_PERF

  ### 📦 CI/CD
  $CHANGES_FOR_CATEGORY_CI

  **Contributors**:
  $CONTRIBUTORS
