changelog:
<<<<<<< HEAD
  - title: 'ðŸ”§ Breaking Changes'
    labels:
      - breaking-change
  - title: 'ðŸš€ New Features'
    labels:
      - new-feature
  - title: 'ðŸ› Bug Fixes'
    labels:
      - bug-fix
=======
  categories:
    - title: "ðŸ”§ Breaking Changes"
      labels:
        - breaking-change
    - title: "ðŸš€ New Features"
      labels:
        - new-feature
    - title: "ðŸ› Bug Fixes"
      labels:
        - bug-fix
>>>>>>> cde85af0cb9f41e217537ada685da7a893764fed
