name-template: 'Release v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feat'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🧹 Chores'
    label: 'chore'
  - title: '📝 Documentation'
    label: 'docs'
  - title: '🔧 Refactoring'
    label: 'refactor'
  - title: '🔍 Tests'
    label: 'test'
  - title: '💄 Style'
    label: 'style'
  - title: '⚡️ Performance'
    label: 'perf'
  - title: '📦 CI/CD'
    label: 'ci'
change-template: '- $TITLE (#$NUMBER) by @${{PR.author.login}}'
template: |
  ## Changes in this Release

  ### 🚀 Features

  ### 🐛 Bug Fixes

  ### 🧹 Chores

  ### 📝 Documentation

  ### 🔧 Refactoring

  ### 🔍 Tests

  ### 💄 Style

  ### ⚡️ Performance

  ### 📦 CI/CD

  **Contributors**:

