name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Breaking Changes'
    labels: 
      - 'breaking changes'
  - title: 'New Features'
    labels:
      - 'feat'
  - title: 'Fixes'
    labels:
      - 'fix'
  - title: 'Updates'
    labels:
      - 'chore'
      - 'docs'
      - 'refactor'
      - 'test'
change-template: '- $TITLE ([#$NUMBER]($URL))'
template: |
  ## What's Changed
  $CHANGES
