name-template: 'Release v$NEXT_PATCH_VERSION 🌟'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 New Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🛠 Maintenance'
    label: 'chore'
change-template: '- $TITLE (#$NUMBER) @${{PR.author.login}}'
template: |
  ## Changes
  $CHANGES

  **Contributors**:
  $CONTRIBUTORS
