changelog:
  exclude:
    labels:
      - ignore-for-release  # Puedes agregar más etiquetas que quieras excluir
  categories:
    - title: '🔧 Breaking Changes'
      labels:
        - breaking-change
    - title: '🚀 New Features'
      labels:
        - new-feature
    - title: '🐛 Bug Fixes'
      labels:
        - bug-fix
    - title: '📝 Documentation'
      labels:
        - documentation
    - title: '🛠 Code Refactoring'
      labels:
        - refactor
    - title: '🎨 Styling'
      labels:
        - style
    - title: '🔍 Tests'
      labels:
        - test
    - title: '🏗 Build'
      labels:
        - build
    - title: '⚙️ Chore'
      labels:
        - chore
    - title: '⏪ Reverts'
      labels:
        - revert
    - title: '⏩ Performance Improvements'
      labels:
        - perf
    - title: '🔄 Continuous Integration'
      labels:
        - ci
    - title: '💚 Maintenance'
      labels:
        - maintenance
