repos:
  - repo: local
    hooks:
      - id: commit-message-check
        name: Check commit message format
        entry: bash -c 'echo "Pre-commit is running"'
        language: system
        stages: [commit-msg]
