repos:
  - repo: local
    hooks:
      - id: commit-message-check
        name: Check commit message format
        entry: bash -c 'echo "Pre-commit is running"'
        language: system
        stages: [commit-msg]

      - id: pre-isort-notification
        name: Notify before running isort
        entry: bash -c 'echo "Running isort to sort imports..."'
        language: system
        always_run: true
        stages: [commit]

      - id: pre-black-notification
        name: Notify before running black
        entry: bash -c 'echo "Running black to format code..."'
        language: system
        always_run: true
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  
    hooks:
      - id: isort
        args: ["--profile=black", "--check"]  
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 23.1.0  
    hooks:
      - id: black
        args: ["--check"]
        stages: [commit]
