name: Draft Release

on:
  workflow_dispatch:



jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Draft Release
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
