# .github/workflows/pr-track.yml
name: Track Merged PRs

on:
  pull_request:
    types: [closed]

jobs:
  track_pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get PR details
        id: pr_details
        run: |
          echo "PR_TITLE=$(echo '${{ github.event.pull_request.title }}')" >> $GITHUB_ENV
          echo "PR_AUTHOR=$(echo '${{ github.event.pull_request.user.login }}')" >> $GITHUB_ENV
          echo "PR_NUMBER=$(echo '${{ github.event.pull_request.number }}')" >> $GITHUB_ENV

      - name: Extract Category from PR Title
        id: extract_category
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          # Expresión regular para capturar la categoría del formato [DS-###] - feat/fix/chore/etc
          if [[ "$PR_TITLE" =~ \[[DS\-0-9]+\]\ \-\ (feat|fix|chore) ]]; then
            CATEGORY=${BASH_REMATCH[2]}  # Captura la categoría en el segundo grupo
            echo "PR_CATEGORY=$CATEGORY" >> $GITHUB_ENV
            echo "Categoria encontrada: $CATEGORY"
          else
            echo "PR_CATEGORY=other" >> $GITHUB_ENV
            echo "No se encontró categoría válida. Título del PR: $PR_TITLE"
          fi

      - name: Debug category output
        run: echo "La categoría extraída es: ${{ env.PR_CATEGORY }}"

      - name: Store PR in Changelog File
        run: |
          PR_LINE="* PR #${{ env.PR_NUMBER }} - ${{ env.PR_TITLE }} by @${{ env.PR_AUTHOR }}"
          
          if [ "${{ env.PR_CATEGORY }}" == "feat" ]; then
            echo "New Features: $PR_LINE" >> CHANGELOG.md
          elif [ "${{ env.PR_CATEGORY }}" == "fix" ]; then
            echo "Fixes: $PR_LINE" >> CHANGELOG.md
          elif [ "${{ env.PR_CATEGORY }}" == "chore" ]; then
            echo "Updates: $PR_LINE" >> CHANGELOG.md
          else
            echo "Other Changes: $PR_LINE" >> CHANGELOG.md
          fi


      - name: Commit changelog update
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "[Auto] Update CHANGELOG for PR #${{ env.PR_NUMBER }}"
          git push origin main
