name-template: 'Release ${{nextRelease}}'

categories:
  - title: "New Features"
    labels: [ "feat" ]
  - title: "Fixes"
    labels: [ "fix" ]
  - title: "Updates"
    labels: [ "chore", "refactor", "docs" ]

change-template: '* PR #{{number}} - {{title}} by @{{author}}'
template: |
  ## What's Changed

  $CHANGES
