name: Draft Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Draft Release
        uses: release-drafter/release-drafter@v5
